#V2
version: '3.8'

services:
  locust-master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./mnt:/mnt/locust
    command: ["-f", "/mnt/locust/locustfile.py", "--master"]
    environment:
      - LOCUST_MODE=master
      - LOCUST_HOST=http://demo:8080
    networks:
      - app_network
    depends_on:
      - demo
      - db

  locust-worker:
    image: locustio/locust
    container_name: locust-worker
    volumes:
      - ./mnt:/mnt/locust
    command: ["-f", "/mnt/locust/locustfile.py", "--worker", "--master-host", "locust-master"]
    environment:
      - LOCUST_MODE=worker
      - LOCUST_HOST=http://demo:8080
    depends_on:
      - locust-master
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


