
version: '3.8'

services:
  demo:
    container_name: password_gen_demo
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PasswordGenerator_DB
      SPRING_DATASOURCE_USERNAME: user_n
      SPRING_DATASOURCE_PASSWORD: user_password
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: password_gen_db
    restart: always
    environment:
      POSTGRES_DB: PasswordGenerator_DB
      POSTGRES_USER: user_n
      POSTGRES_PASSWORD: user_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./PasswordGenerator_DB.sql:/docker-entrypoint-initdb.d/PasswordGenerator_DB.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

  frontend:
    container_name: password_gen_frontend
    build:
      context: ../frontend/password-generator
      dockerfile: Dockerfile-frontend

    ports:
      - "80:80"


    depends_on:
      - demo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge






