version: '3'
services:
  demo:
    container_name: password_gen_demo
    restart: on-failure
    #build: ./
    build:
      context: .
      dockerfile: Dockerfile

    links:
     - db:db


    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PasswordGenerator_DB
      #SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/PasswordGenerator_DB
      SPRING_DATASOURCE_USERNAME: user_n
      SPRING_DATASOURCE_PASSWORD: user_password

    #Додав залежність від бази данних
    depends_on:
        - db

    networks:
      - app_network

  db:
    image: postgres:13
    container_name: password_gen_db
    restart: always
    environment:
      POSTGRES_DB: PasswordGenerator_DB
      POSTGRES_USER: user_n
      POSTGRES_PASSWORD: user_password

    volumes:
      # Монтуємо локальну директорію ./data/db в контейнер,
      #щоб зберігати дані бази даних
      - ./data/db:/var/lib/postgresql/data

      # Монтуємо SQL скрипт для ініціалізації бази даних,
      #щоб він автоматично виконувався при старті контейнера
      - ./PasswordGenerator_DB.sql:/docker-entrypoint-initdb.d/PasswordGenerator_DB.sql

    ports:
      - "5432:5432"

    networks:
      - app_network

networks:
  app_network:
    driver: bridge



#  docker compose down -v
#Або це видалить монтовані данні docker compose down -v; Remove-Item -Recurse -Force .\data\db

#  docker compose up --build -d

#Список таблиць у PostgreSQL через Docker
# docker exec -it password_gen_db psql -U user_n -d PasswordGenerator_DB -c "\dt"

#Перевірка логів контейнерів
#docker logs password_gen_demo
#docker logs password_gen_db

#Перезапуск усіх сервісів
#docker-compose restart



#???
#1)Перевірте з'єднання з базою даних:
#docker exec -it password_gen_db psql -U user_n -d PasswordGenerator_DB
#2)Перевірити всі користувачів у базі даних:
#\du
#3)Перевірка наявності таблиць у базі даних:
#\dt
#4)Перевірка прав доступу для користувача:
#\l
#5)Вихід:
#\q

  #Очистити директорію з базою
  #Remove-Item -Recurse -Force .\data\db

#docker exec -it password_gen_demo /bin/bash


#docker system prune -a